apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krx-rule-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krx-rule-index
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
